### ISSUE TITLE
create a minimalist application in C for the desktop notification area

### ISSUE THREAD

**Issue by fdechelle** [armadito/armadito-web-ui#8]
- application has a desktop notification area icon (aka systray)
- icon has a menu
- icon shows important notifications
- application uses the REST API

**Comment by fdechelle** [comment]
on linux, systray application can launch the default browser on armadito web server using:
xdg-open http://localhost:8888/app/index.html
works also with sensible-browser instead of xdg-open

**Comment by vhamon** [comment]
moved to armadito-systray-ui
